version: "2"

run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - revive

issues:
  exclude-rules:
    - path: 'extracts/'
      linters:
        - revive
        - gofmt
