version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: var-naming
          disabled: true

formatters:
  enable:
    - gofmt
