name: "Steinel CAM Bridge Beta"
description: "Standalone ONVIF, 2-Way Audio & MQTT Bridge für Steinel L 625 CAM SC"
version: "1.1.0-beta.9"
slug: "steinel_cam_bridge_beta"
url: "https://github.com/Afrouper/steinel-cam-bridge"
panel_icon: "mdi:cctv"
arch:
  - aarch64
  - amd64
init: false
host_network: true
hassio_api: true
homeassistant_api: true
services:
  - "mqtt:want"
environment:
  IS_BETA: "true"
options:
  camera_ip: ""
  camera_type: "auto"
  qr_code: ""
  reset_pairing: false
  camera_password: ""
  camera_user: "admin"
  resolution: "1080p"
  audio_codec: "aac"
  rtsp_port: 8554
  onvif_port: 8000
  debug: false
schema:
  camera_ip: "str"
  camera_type: "list(auto|l625|l620)?"
  qr_code: "str?"
  reset_pairing: "bool?"
  camera_password: "password?"
  camera_user: "str?"
  resolution: "list(1080p|720p|360p)"
  audio_codec: "list(aac|pcmu)"
  rtsp_port: "port"
  onvif_port: "port"
  debug: "bool?"
  mqtt_broker: "str?"
  mqtt_user: "str?"
  mqtt_password: "password?"
  mqtt_topic_prefix: "str?"
  mqtt_discovery_prefix: "str?"
image: "ghcr.io/afrouper/steinel-cam-bridge"
